#pragma once

#include <stdint.h>

constexpr uint8_t MAX_CONSECUTIVE_SAMPLES = UINT8_MAX;

enum class DeviceState : uint8_t {
  STANDBY,
  ID_INPUT,
  WAIT_ID_RESULT,
  REGISTRATION_READY,
  CALIBRATION_READY,
  PATTERN_INPUT,
  PRESSURE_MONITOR,
  WAIT_CAPTURE_RESULT,
  TIMED_MESSAGE,
  AUTH_SUCCESS,
};

enum class DeviceProtocolMode : uint8_t {
  IDLE,
  AUTHENTICATION,
  REGISTRATION_FIRST,
  REGISTRATION_SECOND,
  CALIBRATION,
  PRESSURE_MONITOR,
  AUTH_SUCCESS,
};

enum class MessageKind : uint8_t {
  CALIBRATION_REQUIRED,
  UNREGISTERED_USER,
  WRONG_PATTERN,
  NOT_USER,
  COMMUNICATION_ERROR,
  PI_ERROR,
  PATTERN_DATA_ERROR,
  PATTERN_TIMEOUT,
  AUTH_PATTERN_NOT_ENTERED,
  REGISTRATION_PATTERN_NOT_ENTERED,
  PATTERN_INPUT_CANCELLED,
  OPERATION_CANCELLED,
  CALIBRATION_SUCCESS,
  CAPTURE_FAILED,
  REGISTRATION_SUCCESS,
  REGISTRATION_RETRY,
  REGISTRATION_RESTART,
};

enum class CaptureMode : uint8_t {
  NONE,
  AUTHENTICATION,
  CALIBRATION,
  REGISTRATION_FIRST,
  REGISTRATION_SECOND,
};
